const DAILY_UPDATE_CACHE_TTL = 60 * 60 * 24
const HOURS3_CACHE_TTL = 60 * 60 * 3
const HOUR_CACHE_TTL = 60 * 60 * 1
const DEFAULT_CACHE_TIME = 60 * 60

export { DAILY_UPDATE_CACHE_TTL, DEFAULT_CACHE_TIME, HOURS3_CACHE_TTL, HOUR_CACHE_TTL }
