import { db } from '../pg'
import { companies } from '../schema'

const companiesData = [
	{ name: 'Apple Inc.', symbol: 'AAPL' },
	{ name: 'Airbnb, Inc.', symbol: 'ABNB' },
	{ name: 'Adobe Inc.', symbol: 'ADBE' },
	{ name: 'Autodesk, Inc.', symbol: 'ADSK' },
	{ name: 'C3.ai, Inc.', symbol: 'AI' },
	{ name: 'Akamai Technologies, Inc.', symbol: 'AKAM' },
	{ name: 'Applied Materials, Inc.', symbol: 'AMAT' },
	{ name: 'Advanced Micro Devices, Inc.', symbol: 'AMD' },
	{ name: 'Amazon.com, Inc.', symbol: 'AMZN' },
	{ name: 'Arista Networks, Inc.', symbol: 'ANET' },
	{ name: 'Asana, Inc.', symbol: 'ASAN' },
	{ name: 'ASML Holding N.V.', symbol: 'ASML' },
	{ name: 'Broadcom Inc.', symbol: 'AVGO' },
	{ name: 'Alteryx, Inc.', symbol: 'AYX' },
	{ name: 'The Boeing Company', symbol: 'BA' },
	{ name: 'BlackBerry Limited', symbol: 'BB' },
	{ name: 'Caterpillar Inc.', symbol: 'CAT' },
	{ name: 'ChargePoint Holdings, Inc.', symbol: 'CHPT' },
	{ name: 'Chewy, Inc.', symbol: 'CHWY' },
	{ name: 'Clean Energy Fuels Corp.', symbol: 'CLNE' },
	{ name: 'CME Group Inc.', symbol: 'CME' },
	{ name: 'Coinbase Global, Inc.', symbol: 'COIN' },
	{ name: 'ConocoPhillips', symbol: 'COP' },
	{ name: 'Costco Wholesale Corporation', symbol: 'COST' },
	{ name: 'Salesforce, Inc.', symbol: 'CRM' },
	{ name: 'Cerence Inc.', symbol: 'CRNC' },
	{ name: 'CRISPR Therapeutics AG', symbol: 'CRSP' },
	{ name: 'Cirrus Logic, Inc.', symbol: 'CRUS' },
	{ name: 'CrowdStrike Holdings, Inc.', symbol: 'CRWD' },
	{ name: 'Cisco Systems, Inc.', symbol: 'CSCO' },
	{ name: 'Cintas Corporation', symbol: 'CTAS' },
	{ name: 'Chevron Corporation', symbol: 'CVX' },
	{ name: 'CyberArk Software Ltd.', symbol: 'CYBR' },
	{ name: 'Datadog, Inc.', symbol: 'DDOG' },
	{ name: 'Digi International Inc.', symbol: 'DGII' },
	{ name: 'The Walt Disney Company', symbol: 'DIS' },
	{ name: 'DigitalOcean Holdings, Inc.', symbol: 'DOCN' },
	{ name: 'Doximity, Inc.', symbol: 'DOCS' },
	{ name: 'DocuSign, Inc.', symbol: 'DOCU' },
	{ name: 'Dynatrace, Inc.', symbol: 'DT' },
	{ name: 'Enphase Energy, Inc.', symbol: 'ENPH' },
	{ name: 'Equinix, Inc.', symbol: 'EQIX' },
	{ name: 'Eaton Corporation plc', symbol: 'ETN' },
	{ name: 'E2open Parent Holdings, Inc.', symbol: 'ETWO' },
	{ name: 'Ford Motor Company', symbol: 'F' },
	{ name: 'FuelCell Energy, Inc.', symbol: 'FCEL' },
	{ name: 'FedEx Corporation', symbol: 'FDX' },
	{ name: 'F5, Inc.', symbol: 'FFIV' },
	{ name: 'First Solar, Inc.', symbol: 'FSLR' },
	{ name: 'Fortinet, Inc.', symbol: 'FTNT' },
	{ name: 'General Dynamics Corporation', symbol: 'GD' },
	{ name: 'Barrick Gold Corporation', symbol: 'GOLD' },
	{ name: 'Alphabet Inc.', symbol: 'GOOG' },
	{ name: 'Honeywell International Inc.', symbol: 'HON' },
	{ name: 'HubSpot, Inc.', symbol: 'HUBS' },
	{ name: 'Hexcel Corporation', symbol: 'HXL' },
	{ name: 'Intel Corporation', symbol: 'INTC' },
	{ name: 'Intuit Inc.', symbol: 'INTU' },
	{ name: 'Samsara Inc.', symbol: 'IOT' },
	{ name: 'Iridium Communications Inc.', symbol: 'IRDM' },
	{ name: 'Intuitive Surgical, Inc.', symbol: 'ISRG' },
	{ name: 'Lockheed Martin Corporation', symbol: 'LMT' },
	{ name: 'Cheniere Energy, Inc.', symbol: 'LNG' },
	{ name: 'Lam Research Corporation', symbol: 'LRCX' },
	{ name: 'Lululemon Athletica Inc.', symbol: 'LULU' },
	{ name: 'Mastercard Incorporated', symbol: 'MA' },
	{ name: 'Mobileye Global Inc.', symbol: 'MBLY' },
	{ name: 'MongoDB, Inc.', symbol: 'MDB' },
	{ name: 'MercadoLibre, Inc.', symbol: 'MELI' },
	{ name: 'Meta Platforms, Inc.', symbol: 'META' },
	{ name: 'MP Materials Corp.', symbol: 'MP' },
	{ name: 'Marvell Technology, Inc.', symbol: 'MRVL' },
	{ name: 'Microsoft Corporation', symbol: 'MSFT' },
	{ name: 'Matador Resources Company', symbol: 'MTDR' },
	{ name: 'MasTec, Inc.', symbol: 'MTZ' },
	{ name: 'Micron Technology, Inc.', symbol: 'MU' },
	{ name: 'NextEra Energy, Inc.', symbol: 'NEE' },
	{ name: 'Cloudflare, Inc.', symbol: 'NET' },
	{ name: 'Netflix, Inc.', symbol: 'NFLX' },
	{ name: 'NIKE, Inc.', symbol: 'NKE' },
	{ name: 'ServiceNow, Inc.', symbol: 'NOW' },
	{ name: 'NVIDIA Corporation', symbol: 'NVDA' },
	{ name: 'NXP Semiconductors N.V.', symbol: 'NXPI' },
	{ name: 'Okta, Inc.', symbol: 'OKTA' },
	{ name: 'ON Semiconductor Corporation', symbol: 'ON' },
	{ name: 'Oracle Corporation', symbol: 'ORCL' },
	{ name: 'Occidental Petroleum Corporation', symbol: 'OXY' },
	{ name: 'Palo Alto Networks, Inc.', symbol: 'PANW' },
	{ name: 'UiPath Inc.', symbol: 'PATH' },
	{ name: 'PG&E Corporation', symbol: 'PCG' },
	{ name: 'Pinterest, Inc.', symbol: 'PINS' },
	{ name: 'Palantir Technologies Inc.', symbol: 'PLTR' },
	{ name: 'Plug Power Inc.', symbol: 'PLUG' },
	{ name: 'PayPal Holdings, Inc.', symbol: 'PYPL' },
	{ name: 'QUALCOMM Incorporated', symbol: 'QCOM' },
	{ name: 'Qorvo, Inc.', symbol: 'QRVO' },
	{ name: 'QuantumScape Corporation', symbol: 'QS' },
	{ name: 'Rivian Automotive, Inc.', symbol: 'RIVN' },
	{ name: 'RTX Corporation', symbol: 'RTX' },
	{ name: 'Sunrun Inc.', symbol: 'RUN' },
	{ name: 'SentinelOne, Inc.', symbol: 'S' },
	{ name: 'Sea Limited', symbol: 'SE' },
	{ name: 'SolarEdge Technologies, Inc.', symbol: 'SEDG' },
	{ name: 'Shopify Inc.', symbol: 'SHOP' },
	{ name: 'Schlumberger Limited', symbol: 'SLB' },
	{ name: 'Snap Inc.', symbol: 'SNAP' },
	{ name: 'Snowflake Inc.', symbol: 'SNOW' },
	{ name: 'Synopsys, Inc.', symbol: 'SNPS' },
	{ name: 'SoundHound AI, Inc.', symbol: 'SOUN' },
	{ name: 'SunPower Corporation', symbol: 'SPWR' },
	{ name: 'Block, Inc.', symbol: 'SQ' },
	{ name: 'Suncor Energy Inc.', symbol: 'SU' },
	{ name: 'Sunworks, Inc.', symbol: 'SUNW' },
	{ name: 'Skyworks Solutions, Inc.', symbol: 'SWKS' },
	{ name: 'Teck Resources Limited', symbol: 'TECK' },
	{ name: 'T-Mobile US, Inc.', symbol: 'TMUS' },
	{ name: 'Tesla, Inc.', symbol: 'TSLA' },
	{ name: 'The Trade Desk, Inc.', symbol: 'TTD' },
	{ name: 'Texas Instruments Incorporated', symbol: 'TXN' },
	{ name: 'Unity Software Inc.', symbol: 'U' },
	{ name: 'Uber Technologies, Inc.', symbol: 'UBER' },
	{ name: 'United Rentals, Inc.', symbol: 'URI' },
	{ name: 'Visa Inc.', symbol: 'V' },
	{ name: 'Veeva Systems Inc.', symbol: 'VEEV' },
	{ name: 'Workday, Inc.', symbol: 'WDAY' },
	{ name: 'Exxon Mobil Corporation', symbol: 'XOM' },
	{ name: 'Eli Lilly & Co', symbol: 'LLY' },
	{ name: 'Johnson & Johnson', symbol: 'JNJ' },
	{ name: 'AbbVie Inc.', symbol: 'ABBV' },
	{ name: 'Unitedhealth Group Inc', symbol: 'UNH' },
	{ name: 'Abbott Laboratories', symbol: 'ABT' },
	{ name: 'Merck & Co Inc', symbol: 'MRK' },
	{ name: 'Intuitive Surgical Inc', symbol: 'ISRG' },
	{ name: 'Thermo Fisher Scientific', symbol: 'TMO' },
	{ name: 'Amgen Inc', symbol: 'AMGN' },
	{ name: 'Boston Scientific Corp', symbol: 'BSX' },
	{ name: 'Pfizer Inc', symbol: 'PFE' },
	{ name: 'Gilead Sciences Inc', symbol: 'GILD' },
	{ name: 'Stryker Corp', symbol: 'SYK' },
	{ name: 'Danaher Corp', symbol: 'DHR' },
	{ name: 'Vertex Pharmaceuticals Inc', symbol: 'VRTX' },
	{ name: 'Medtronic plc', symbol: 'MDT' },
	{ name: 'Bristol-Myers Squibb', symbol: 'BMY' },
	{ name: 'McKesson Corp', symbol: 'MCK' },
	{ name: 'CVS Health Corporation', symbol: 'CVS' },
	{ name: 'Elevance Health, Inc.', symbol: 'ELV' },
	{ name: 'Zoetis Inc', symbol: 'ZTS' },
	{ name: 'HCA Healthcare Inc', symbol: 'HCA' },
	{ name: 'Regeneron Pharmaceuticals Inc', symbol: 'REGN' },
	{ name: 'Becton Dickinson & Co', symbol: 'BDX' },
	{ name: 'Cencora, Inc.', symbol: 'COR' },
	{ name: 'Edwards Lifesciences Corp', symbol: 'EW' },
	{ name: 'IDEXX Laboratories Inc', symbol: 'IDXX' },
	{ name: 'Cardinal Health Inc', symbol: 'CAH' },
	{ name: 'ResMed Inc', symbol: 'RMD' },
	{ name: 'Berkshire Hathaway Inc.', symbol: 'BRK.B' },
	{ name: 'JPMorgan Chase & Co.', symbol: 'JPM' },
	{ name: 'Walmart Inc.', symbol: 'WMT' },
	{ name: 'The Home Depot, Inc.', symbol: 'HD' },
	{ name: 'Bank of America Corporation', symbol: 'BAC' },
	{ name: 'The Procter & Gamble Company', symbol: 'PG' },
	{ name: 'General Electric Company', symbol: 'GE' },
	{ name: 'The Coca-Cola Company', symbol: 'KO' },
	{ name: 'International Business Machines Corporation', symbol: 'IBM' },
	{ name: 'Philip Morris International Inc.', symbol: 'PM' },
	{ name: 'Wells Fargo & Company', symbol: 'WFC' },
	{ name: 'Morgan Stanley', symbol: 'MS' },
	{ name: 'The Goldman Sachs Group, Inc.', symbol: 'GS' },
	{ name: 'Linde plc', symbol: 'LIN' },
	{ name: "McDonald's Corporation", symbol: 'MCD' },
	{ name: 'American Express Company', symbol: 'AXP' },
	{ name: 'Union Pacific Corporation', symbol: 'UNP' },
	{ name: "Lowe's Companies, Inc.", symbol: 'LOW' },
	{ name: 'Capital One Financial Corporation', symbol: 'COF' },
	{ name: 'KLA Corporation', symbol: 'KLAC' },
	{ name: 'Deere & Company', symbol: 'DE' },
	{ name: 'Automatic Data Processing, Inc.', symbol: 'ADP' },
	{ name: 'Constellation Energy Corporation', symbol: 'CEG' },
	{ name: 'Chubb Limited', symbol: 'CB' },
	{ name: 'Altria Group, Inc.', symbol: 'MO' },
	{ name: 'Welltower Inc.', symbol: 'WELL' },
	{ name: 'Analog Devices, Inc.', symbol: 'ADI' },
	{ name: 'Comcast Corporation', symbol: 'CMCSA' },
	{ name: 'The Southern Company', symbol: 'SO' },
	{ name: 'Prologis, Inc.', symbol: 'PLD' },
	{ name: 'KKR & Co. Inc.', symbol: 'KKR' },
	{ name: 'Marsh & McLennan Companies, Inc.', symbol: 'MMC' },
	{ name: 'Dell Technologies Inc.', symbol: 'DELL' },
	{ name: 'Duke Energy Corporation', symbol: 'DUK' },
	{ name: 'Newmont Corporation', symbol: 'NEM' },
	{ name: 'Trane Technologies plc', symbol: 'TT' },
	{ name: 'Parker-Hannifin Corporation', symbol: 'PH' },
	{ name: 'Intercontinental Exchange, Inc.', symbol: 'ICE' },
	{ name: 'Northrop Grumman Corporation', symbol: 'NOC' },
	{ name: 'Starbucks Corporation', symbol: 'SBUX' },
	{ name: 'Cadence Design Systems, Inc.', symbol: 'CDNS' },
	{ name: 'Waste Management, Inc.', symbol: 'WM' },
	{ name: 'American Tower Corporation', symbol: 'AMT' },
	{ name: "Moody's Corporation", symbol: 'MCO' },
	{ name: "O'Reilly Automotive, Inc.", symbol: 'ORLY' },
	{ name: 'The Sherwin-Williams Company', symbol: 'SHW' },
	{ name: 'Royal Caribbean Cruises Ltd.', symbol: 'RCL' },
	{ name: 'The Cigna Group', symbol: 'CI' },
	{ name: 'Mondelez International, Inc.', symbol: 'MDLZ' },
	{ name: '3M Company', symbol: 'MMM' },
	{ name: 'Aon plc', symbol: 'AON' },
	{ name: 'Arthur J. Gallagher & Co.', symbol: 'AJG' },
	{ name: 'Ecolab Inc.', symbol: 'ECL' },
	{ name: 'The Williams Companies, Inc.', symbol: 'WMB' },
	{ name: 'Motorola Solutions, Inc.', symbol: 'MSI' },
	{ name: 'Howmet Aerospace Inc.', symbol: 'HWM' },
	{ name: 'The Bank of New York Mellon Corporation', symbol: 'BK' },
	{ name: 'The PNC Financial Services Group, Inc.', symbol: 'PNC' },
	{ name: 'TransDigm Group Incorporated', symbol: 'TDG' },
	{ name: 'Illinois Tool Works Inc.', symbol: 'ITW' },
	{ name: 'Corning Incorporated', symbol: 'GLW' },
	{ name: 'Emerson Electric Co.', symbol: 'EMR' },
	{ name: 'Marriott International, Inc.', symbol: 'MAR' },
	{ name: 'U.S. Bancorp', symbol: 'USB' },
	{ name: 'Republic Services, Inc.', symbol: 'RSG' },
	{ name: 'United Parcel Service, Inc.', symbol: 'UPS' },
	{ name: 'Johnson Controls International plc', symbol: 'JCI' },
	{ name: 'Monster Beverage Corporation', symbol: 'MNST' },
	{ name: 'AutoZone, Inc.', symbol: 'AZO' },
	{ name: 'Apollo Global Management, Inc.', symbol: 'APO' },
	{ name: 'Vistra Corp.', symbol: 'VST' },
	{ name: 'Fiserv, Inc.', symbol: 'FI' },
	{ name: 'CSX Corporation', symbol: 'CSX' },
	{ name: 'Simon Property Group, Inc.', symbol: 'SPG' },
	{ name: 'Norfolk Southern Corporation', symbol: 'NSC' },
	{ name: 'TE Connectivity plc', symbol: 'TEL' },
	{ name: 'Colgate-Palmolive Company', symbol: 'CL' },
	{ name: 'American Electric Power Company, Inc.', symbol: 'AEP' },
	{ name: 'Quanta Services, Inc.', symbol: 'PWR' },
	{ name: 'Hilton Worldwide Holdings Inc.', symbol: 'HLT' },
	{ name: 'The Travelers Companies, Inc.', symbol: 'TRV' },
	{ name: 'Kinder Morgan, Inc.', symbol: 'KMI' },
	{ name: 'Aflac Incorporated', symbol: 'AFL' },
	{ name: 'EOG Resources, Inc.', symbol: 'EOG' },
	{ name: 'Sempra', symbol: 'SRE' },
	{ name: 'Freeport-McMoRan Inc.', symbol: 'FCX' },
	{ name: 'Air Products and Chemicals, Inc.', symbol: 'APD' },
	{ name: 'Cummins Inc.', symbol: 'CMI' },
	{ name: 'Axon Enterprise, Inc.', symbol: 'AXON' },
	{ name: 'Marathon Petroleum Corporation', symbol: 'MPC' },
	{ name: 'Roper Technologies, Inc.', symbol: 'ROP' },
	{ name: 'L3Harris Technologies, Inc.', symbol: 'LHX' },
	{ name: 'Truist Financial Corporation', symbol: 'TFC' },
	{ name: 'The Allstate Corporation', symbol: 'ALL' },
	{ name: 'Realty Income Corporation', symbol: 'O' },
	{ name: 'Chipotle Mexican Grill, Inc.', symbol: 'CMG' },
	{ name: 'MetLife, Inc.', symbol: 'MET' },
	{ name: 'General Motors Company', symbol: 'GM' },
	{ name: 'Fastenal Company', symbol: 'FAST' },
	{ name: 'Dominion Energy, Inc.', symbol: 'D' },
	{ name: 'Public Storage', symbol: 'PSA' },
	{ name: 'Phillips 66', symbol: 'PSX' },
	{ name: 'Nasdaq, Inc.', symbol: 'NDAQ' },
	{ name: 'Electronic Arts Inc.', symbol: 'EA' },
	{ name: 'Valero Energy Corporation', symbol: 'VLO' },
	{ name: 'PACCAR Inc', symbol: 'PCAR' },
	{ name: 'Carrier Global Corporation', symbol: 'CARR' },
	{ name: 'Ross Stores, Inc.', symbol: 'ROST' },
	{ name: 'Xcel Energy Inc.', symbol: 'XEL' },
	{ name: 'Garmin Ltd.', symbol: 'GRMN' },
	{ name: 'Exelon Corporation', symbol: 'EXC' },
	{ name: 'Take-Two Interactive Software, Inc.', symbol: 'TTWO' },
	{ name: 'Seagate Technology Holdings plc', symbol: 'STX' },
	{ name: 'W.W. Grainger, Inc.', symbol: 'GWW' },
	{ name: 'Ameriprise Financial, Inc.', symbol: 'AMP' },
	{ name: 'D.R. Horton, Inc.', symbol: 'DHI' },
	{ name: 'Paychex, Inc.', symbol: 'PAYX' },
	{ name: 'American International Group, Inc.', symbol: 'AIG' },
	{ name: 'The Kroger Co.', symbol: 'KR' },
	{ name: 'Baker Hughes Company', symbol: 'BKR' },
	{ name: 'CBRE Group, Inc.', symbol: 'CBRE' },
	{ name: 'ONEOK, Inc.', symbol: 'OKE' },
	{ name: 'Monolithic Power Systems, Inc.', symbol: 'MPWR' },
	{ name: 'Entergy Corporation', symbol: 'ETR' },
	{ name: 'Crown Castle Inc.', symbol: 'CCI' },
	{ name: 'Copart, Inc.', symbol: 'CPRT' },
	{ name: 'Warner Bros. Discovery, Inc.', symbol: 'WBD' },
	{ name: 'MSCI Inc.', symbol: 'MSCI' },
	{ name: 'Corteva, Inc.', symbol: 'CTVA' },
	{ name: 'AMETEK, Inc.', symbol: 'AME' },
	{ name: 'Diamondback Energy, Inc.', symbol: 'FANG' },
	{ name: 'eBay Inc.', symbol: 'EBAY' },
	{ name: 'Public Service Enterprise Group Incorporated', symbol: 'PEG' },
	{ name: 'Fair Isaac Corporation', symbol: 'FICO' },
	{ name: 'Vulcan Materials Company', symbol: 'VMC' },
	{ name: 'Charter Communications, Inc.', symbol: 'CHTR' },
	{ name: 'Kimberly-Clark Corporation', symbol: 'KMB' },
	{ name: 'Western Digital Corporation', symbol: 'WDC' },
	{ name: 'Yum! Brands, Inc.', symbol: 'YUM' },
	{ name: 'The Hershey Company', symbol: 'HSY' },
	{ name: 'Target Corporation', symbol: 'TGT' },
	{ name: 'Agilent Technologies, Inc.', symbol: 'A' },
	{ name: 'Martin Marietta Materials, Inc.', symbol: 'MLM' },
	{ name: 'Sysco Corporation', symbol: 'SYY' },
	{ name: 'Rockwell Automation, Inc.', symbol: 'ROK' },
	{ name: 'Delta Air Lines, Inc.', symbol: 'DAL' },
	{ name: 'TKO Group Holdings, Inc.', symbol: 'TKO' },
	{ name: 'WEC Energy Group, Inc.', symbol: 'WEC' },
	{ name: 'Consolidated Edison, Inc.', symbol: 'ED' },
	{ name: 'Carnival Corporation & plc', symbol: 'CCL' },
	{ name: 'The Hartford Insurance Group, Inc.', symbol: 'HIG' },
	{ name: 'Live Nation Entertainment, Inc.', symbol: 'LYV' },
	{ name: 'Xylem Inc.', symbol: 'XYL' },
	{ name: 'Otis Worldwide Corporation', symbol: 'OTIS' },
	{ name: 'Keurig Dr Pepper Inc.', symbol: 'KDP' },
	{ name: 'Fidelity National Information Services, Inc.', symbol: 'FIS' },
	{ name: 'Prudential Financial, Inc.', symbol: 'PRU' },
	{ name: 'Arch Capital Group Ltd.', symbol: 'ACGL' },
	{ name: 'Las Vegas Sands Corp.', symbol: 'LVS' },
	{ name: 'Verisk Analytics, Inc.', symbol: 'VRSK' },
	{ name: 'Humana Inc.', symbol: 'HUM' },
	{ name: 'IQVIA Holdings Inc.', symbol: 'IQV' },
	{ name: 'EQT Corporation', symbol: 'EQT' },
	{ name: 'VICI Properties Inc.', symbol: 'VICI' },
	{ name: 'Willis Towers Watson Public Limited Company', symbol: 'WTW' },
	{ name: 'Targa Resources Corp.', symbol: 'TRGP' },
	{ name: 'Westinghouse Air Brake Technologies Corporation', symbol: 'WAB' },
	{ name: 'Microchip Technology Incorporated', symbol: 'MCHP' },
	{ name: 'GE HealthCare Technologies Inc.', symbol: 'GEHC' },
	{ name: 'Hewlett Packard Enterprise Company', symbol: 'HPE' },
	{ name: 'Cognizant Technology Solutions Corporation', symbol: 'CTSH' },
	{ name: 'CoStar Group, Inc.', symbol: 'CSGP' },
	{ name: 'Raymond James Financial, Inc.', symbol: 'RJF' },
	{ name: 'Kenvue Inc.', symbol: 'KVUE' },
	{ name: "Brown & Brown, Inc.", symbol: 'BRO' },
	{ name: 'The Estée Lauder Companies Inc.', symbol: 'EL' },
	{ name: 'State Street Corporation', symbol: 'STT' },
	{ name: 'Extra Space Storage Inc.', symbol: 'EXR' },
	{ name: 'Super Micro Computer, Inc.', symbol: 'SMCI' },
	{ name: 'United Airlines Holdings, Inc.', symbol: 'UAL' },
	{ name: 'NRG Energy, Inc.', symbol: 'NRG' },
	{ name: 'Ventas, Inc.', symbol: 'VTR' },
	{ name: 'DuPont de Nemours, Inc.', symbol: 'DD' },
	{ name: 'Interactive Brokers Group, Inc.', symbol: 'IBKR' },
	{ name: 'Nucor Corporation', symbol: 'NUE' },
	{ name: 'Lennar Corporation', symbol: 'LEN' },
	{ name: 'Ingersoll Rand Inc.', symbol: 'IR' },
	{ name: 'Iron Mountain Incorporated', symbol: 'IRM' },
	{ name: 'The Kraft Heinz Company', symbol: 'KHC' },
	{ name: 'EMCOR Group, Inc.', symbol: 'EME' },
	{ name: 'W. R. Berkley Corporation', symbol: 'WRB' },
	{ name: 'Archer-Daniels-Midland Company', symbol: 'ADM' },
	{ name: 'DTE Energy Company', symbol: 'DTE' },
	{ name: 'American Water Works Company, Inc.', symbol: 'AWK' },
	{ name: 'Kellanova', symbol: 'K' },
	{ name: 'Tractor Supply Company', symbol: 'TSCO' },
	{ name: 'Equifax Inc.', symbol: 'EFX' },
	{ name: 'Atmos Energy Corporation', symbol: 'ATO' },
	{ name: 'M&T Bank Corporation', symbol: 'MTB' },
	{ name: 'Old Dominion Freight Line, Inc.', symbol: 'ODFL' },
	{ name: 'Ameren Corporation', symbol: 'AEE' },
	{ name: 'Rollins, Inc.', symbol: 'ROL' },
	{ name: 'PPL Corporation', symbol: 'PPL' },
	{ name: 'Keysight Technologies, Inc.', symbol: 'KEYS' },
	{ name: 'Fifth Third Bancorp', symbol: 'FITB' },
	{ name: 'Broadridge Financial Solutions, Inc.', symbol: 'BR' },
	{ name: 'FirstEnergy Corp.', symbol: 'FE' },
	{ name: 'Eversource Energy', symbol: 'ES' },
	{ name: 'Teledyne Technologies Incorporated', symbol: 'TDY' },
	{ name: 'General Mills, Inc.', symbol: 'GIS' },
	{ name: 'AvalonBay Communities, Inc.', symbol: 'AVB' },
	{ name: 'Mettler-Toledo International Inc.', symbol: 'MTD' },
	{ name: 'Expedia Group, Inc.', symbol: 'EXPE' },
	{ name: 'CenterPoint Energy, Inc.', symbol: 'CNP' },
	{ name: 'Cboe Global Markets, Inc.', symbol: 'CBOE' },
	{ name: 'Fox Corporation', symbol: 'FOXA' },
	{ name: 'DexCom, Inc.', symbol: 'DXCM' },
	{ name: 'Synchrony Financial', symbol: 'SYF' },
	{ name: 'Veralto Corporation', symbol: 'VLTO' },
	{ name: 'Cincinnati Financial Corporation', symbol: 'CINF' },
	{ name: 'Constellation Brands, Inc.', symbol: 'STZ' },
	{ name: 'Ulta Beauty, Inc.', symbol: 'ULTA' },
	{ name: 'VeriSign, Inc.', symbol: 'VRSN' },
	{ name: 'Equity Residential', symbol: 'EQR' },
	{ name: 'Fox Corporation', symbol: 'FOX' },
	{ name: 'Expand Energy Corporation', symbol: 'EXE' },
	{ name: 'Leidos Holdings, Inc.', symbol: 'LDOS' },
	{ name: 'International Paper Company', symbol: 'IP' },
	{ name: 'HP Inc.', symbol: 'HPQ' },
	{ name: 'Northern Trust Corporation', symbol: 'NTRS' },
	{ name: 'PulteGroup, Inc.', symbol: 'PHM' },
	{ name: 'PTC Inc.', symbol: 'PTC' },
	{ name: 'STERIS plc', symbol: 'STE' },
	{ name: 'Labcorp Holdings Inc.', symbol: 'LH' },
	{ name: 'Huntington Bancshares Incorporated', symbol: 'HBAN' },
	{ name: 'NetApp, Inc.', symbol: 'NTAP' },
	{ name: 'Tapestry, Inc.', symbol: 'TPR' },
	{ name: 'T. Rowe Price Group, Inc.', symbol: 'TROW' },
	{ name: 'PPG Industries, Inc.', symbol: 'PPG' },
	{ name: 'CMS Energy Corporation', symbol: 'CMS' },
	{ name: 'Dover Corporation', symbol: 'DOV' },
	{ name: 'Insulet Corporation', symbol: 'PODD' },
	{ name: 'Williams-Sonoma, Inc.', symbol: 'WSM' },
	{ name: 'Dollar General Corporation', symbol: 'DG' },
	{ name: 'Tyler Technologies, Inc.', symbol: 'TYL' },
	{ name: 'Hubbell Incorporated', symbol: 'HUBB' },
	{ name: 'Regions Financial Corporation', symbol: 'RF' },
	{ name: 'Biogen Inc.', symbol: 'BIIB' },
	{ name: 'Accenture plc', symbol: 'ACN' },
	{ name: 'Amphenol Corporation', symbol: 'APH' },
	{ name: 'S&P Global Inc.', symbol: 'SPGI' },
	{ name: 'The Progressive Corporation', symbol: 'PGR' },
	{ name: 'Booking Holdings Inc.', symbol: 'BKNG' },
	{ name: 'The Charles Schwab Corporation', symbol: 'SCHW' },
	{ name: 'GE Vernova Inc.', symbol: 'GEV' },
	{ name: 'The TJX Companies, Inc.', symbol: 'TJX' },
	{ name: 'BlackRock, Inc.', symbol: 'BLK' },
	{ name: 'AT&T Inc.', symbol: 'T' },
	{ name: 'AppLovin Corporation', symbol: 'APP' },
	{ name: 'Blackstone Inc.', symbol: 'BX' },
	{ name: 'DoorDash, Inc.', symbol: 'DASH' },
	{ name: 'Robinhood Markets, Inc.', symbol: 'HOOD' },
]

async function main() {
	console.log('🌱 開始寫入 Seed 資料...');
  
	try {
	  await db.insert(companies).values(companiesData)
		.onConflictDoNothing(); // 建議加上，避免重複執行時報錯
  
	  console.log('✅ Seed 成功！');
	} catch (error) {
	  console.error('❌ Seed 失敗:', error);
	  process.exit(1);
	}
  }
  
  main();